[[plans]]
name = "Node.js"
priority = 1

[plans.detectors]
any = [
  "package.json"
]

[plans.builder]
run = '''
cd $APP_DIR/api
npm install
npx tsc
'''

[plans.runner]
cmd = "node api/dist/main.js"
env = { PORT = "$PORT" }